### ISSUE TITLE
Gerrit doesn't work with intelliJ Ultimate 2016.2 (NoSuchMethodError)

### ISSUE THREAD

**Issue by romainlouvet** [uwolfer/gerrit-intellij-plugin#234]
NoSuchMethodError: com.urswolfer.intellij.plugin.gerrit.ui.RepositoryChangesBrowserProvider$GerritRepositoryChangesBrowser.getDiffAction()Lcom/intellij/openapi/vcs/changes/actions/diff/ShowDiffAction;

**Comment by romainlouvet** [comment]
![capture d ecran 2016-07-20 a 11 25 47](https://cloud.githubusercontent.com/assets/4262374/16981840/db9e004c-4e6c-11e6-9793-02b80b075fd3.png)

**Comment by uwolfer** [comment]
See #231 (or #210) for a solution.
